### ISSUE TITLE
Help with installing

### ISSUE THREAD

**Issue by Nightmare598** [eviscares/arma3_utils#1]
Hi, I would like to give this tool a try in my Arma 3 dedicated server, but I'm quite new to Linux and I dont know how to install this. What files should I download? Or how do I use this?

**Comment by eviscares** [comment]
Hey, sorry, didn't see the issue there for ages.

You can just download all of the files to your linux server and unpack them there.
Then you have to go through the config and see that it is set up for your environment (install paths, users etc.).
Add the mods you want to download to the config file and then just run "./arma3_mod_config_manager.py" to download all the mods you want to have on your server.
Create a list of mods in the configuted folder, and activate it via "./arma3_mod_config_manager.py --name $yourconfigname.cfg" and you should be good to go.
